"""
Auto-generated city building rule (lime_stucco).
Generated by pro.city.building_rules — safe to regenerate with --force-rules.
"""
from pro import *

__version__ = "1.0.0"
__description__ = "Generated city building: lime_stucco"
__tags__ = ["city", "generated", "lime_stucco"]

_PRESET = {
    "height_lo": 4.5,
    "height_hi": 9.5,
    "flat_roof_bias": 0.3,
    "pitch_base": 34,
    "overhang": 0.38,
    "colors": ('#c5d1b8', '#d5e2cf', '#b8c8a8'),
}


@rule
def Begin():
    plot = city_block({"density": 0.5})
    density = float(plot.get("density") or 0.5)
    p = _PRESET

    facade = choice(*p["colors"])
    height = round(
        p["height_lo"] + density * (p["height_hi"] - p["height_lo"]) * float(random(0.85, 1.15)),
        1,
    )

    color(facade)
    extrude(height)
    flat_w = min(0.95, max(0.05, p["flat_roof_bias"] * 0.5 + density * 0.5))
    chance(
        (flat_w, FlatRoof()),
        (1.0 - flat_w, PitchedRoof()),
    )


@rule
def FlatRoof():
    pass


@rule
def PitchedRoof():
    try:
        hip_roof(_PRESET["pitch_base"] + float(random(-4, 4)), _PRESET["overhang"])
    except Exception:
        pass
