"""
Auto-generated city building rule (suburb_mixed).
Generated by pro.city.building_rules — safe to regenerate with --force-rules.
"""
from pro import *

__version__ = "1.0.0"
__description__ = "Generated city building: suburb_mixed"
__tags__ = ["city", "generated", "suburb_mixed"]

_PRESET = {
    "height_lo": 4,
    "height_hi": 9,
    "flat_roof_bias": 0.25,
    "pitch_base": 36,
    "overhang": 0.4,
    "colors": ('#d4b483', '#c5d1b8', '#e8dcc8'),
}


@rule
def Begin():
    plot = city_block({"density": 0.5})
    density = float(plot.get("density") or 0.5)
    p = _PRESET

    facade = choice(*p["colors"])
    height = round(
        p["height_lo"] + density * (p["height_hi"] - p["height_lo"]) * float(random(0.85, 1.15)),
        1,
    )

    color(facade)
    extrude(height)
    flat_w = min(0.95, max(0.05, p["flat_roof_bias"] * 0.5 + density * 0.5))
    chance(
        (flat_w, FlatRoof()),
        (1.0 - flat_w, PitchedRoof()),
    )


@rule
def FlatRoof():
    pass


@rule
def PitchedRoof():
    try:
        hip_roof(_PRESET["pitch_base"] + float(random(-4, 4)), _PRESET["overhang"])
    except Exception:
        pass
