"""
Auto-generated city building rule (office_slab).
Generated by pro.city.building_rules — safe to regenerate with --force-rules.
"""
from pro import *

__version__ = "1.0.0"
__description__ = "Generated city building: office_slab"
__tags__ = ["city", "generated", "office_slab"]

_PRESET = {
    "height_lo": 10,
    "height_hi": 18,
    "flat_roof_bias": 0.9,
    "pitch_base": 25,
    "overhang": 0.2,
    "colors": ('#9aa4ae', '#b0b8c0', '#707880'),
}


@rule
def Begin():
    plot = city_block({"density": 0.5})
    density = float(plot.get("density") or 0.5)
    p = _PRESET

    facade = choice(*p["colors"])
    height = round(
        p["height_lo"] + density * (p["height_hi"] - p["height_lo"]) * float(random(0.85, 1.15)),
        1,
    )

    color(facade)
    extrude(height)
    flat_w = min(0.95, max(0.05, p["flat_roof_bias"] * 0.5 + density * 0.5))
    chance(
        (flat_w, FlatRoof()),
        (1.0 - flat_w, PitchedRoof()),
    )


@rule
def FlatRoof():
    pass


@rule
def PitchedRoof():
    try:
        hip_roof(_PRESET["pitch_base"] + float(random(-4, 4)), _PRESET["overhang"])
    except Exception:
        pass
