"""
Reusable pool of parameterized BCGA building rules for random cities.

Generates examples/generated_rules/building_XX.py once (idempotent unless
force=True). Each file is a density-aware rule with a fixed style preset.
"""
from __future__ import annotations

import os
import random as randomlib
from typing import List, Optional, Sequence


# Deterministic presets (not RNG) so the rule pool is stable across machines.
BUILDING_PRESETS = [
    dict(name="glass_tower", height_lo=18, height_hi=32, flat_roof_bias=0.85, pitch_base=28, overhang=0.25,
         colors=("#8fa8b8", "#a8c0d0", "#6a8494")),
    dict(name="midrise_glass", height_lo=12, height_hi=22, flat_roof_bias=0.7, pitch_base=30, overhang=0.3,
         colors=("#7a9aaa", "#9eb4c2", "#5c7888")),
    dict(name="office_slab", height_lo=10, height_hi=18, flat_roof_bias=0.9, pitch_base=25, overhang=0.2,
         colors=("#9aa4ae", "#b0b8c0", "#707880")),
    dict(name="brick_walkup", height_lo=8, height_hi=14, flat_roof_bias=0.35, pitch_base=32, overhang=0.35,
         colors=("#b8895a", "#a07848", "#c49a6c")),
    dict(name="warm_brick", height_lo=6, height_hi=12, flat_roof_bias=0.3, pitch_base=34, overhang=0.4,
         colors=("#c49a6c", "#b8895a", "#9a7048")),
    dict(name="painted_stucco", height_lo=5, height_hi=11, flat_roof_bias=0.4, pitch_base=33, overhang=0.35,
         colors=("#d9d2c3", "#e8e0d0", "#c8c0b0")),
    dict(name="cream_cottage", height_lo=3.5, height_hi=7, flat_roof_bias=0.15, pitch_base=38, overhang=0.45,
         colors=("#efe8dc", "#e2c4b6", "#d4b483")),
    dict(name="dark_cottage", height_lo=3.5, height_hi=7.5, flat_roof_bias=0.1, pitch_base=40, overhang=0.5,
         colors=("#6e4a30", "#5c3e28", "#8a6040")),
    dict(name="suburb_mixed", height_lo=4, height_hi=9, flat_roof_bias=0.25, pitch_base=36, overhang=0.4,
         colors=("#d4b483", "#c5d1b8", "#e8dcc8")),
    dict(name="pale_modern", height_lo=7, height_hi=15, flat_roof_bias=0.65, pitch_base=28, overhang=0.28,
         colors=("#c5d4dd", "#d8e0e6", "#a8b8c4")),
    dict(name="slate_row", height_lo=6, height_hi=12, flat_roof_bias=0.45, pitch_base=35, overhang=0.32,
         colors=("#7a6b56", "#8a7a64", "#6e6254")),
    dict(name="terracotta", height_lo=5, height_hi=10, flat_roof_bias=0.2, pitch_base=37, overhang=0.42,
         colors=("#b5523a", "#a34430", "#c45c3e")),
    dict(name="lime_stucco", height_lo=4.5, height_hi=9.5, flat_roof_bias=0.3, pitch_base=34, overhang=0.38,
         colors=("#c5d1b8", "#d5e2cf", "#b8c8a8")),
    dict(name="charcoal_loft", height_lo=8, height_hi=16, flat_roof_bias=0.55, pitch_base=30, overhang=0.3,
         colors=("#4a5058", "#5a6068", "#3a4048")),
    dict(name="sandstone", height_lo=5, height_hi=11, flat_roof_bias=0.35, pitch_base=33, overhang=0.36,
         colors=("#d9c2a0", "#e6c36a", "#c4b49a")),
    dict(name="harbour_blue", height_lo=6, height_hi=13, flat_roof_bias=0.5, pitch_base=31, overhang=0.33,
         colors=("#4a6a7a", "#5a7a8a", "#3a5a6a")),
    dict(name="narrow_townhouse", height_lo=7, height_hi=14, flat_roof_bias=0.4, pitch_base=36, overhang=0.3,
         colors=("#a35642", "#9a4a3a", "#8c4032")),
    dict(name="park_edge", height_lo=4, height_hi=8, flat_roof_bias=0.2, pitch_base=38, overhang=0.48,
         colors=("#8b6a45", "#7a5a38", "#a07a50")),
    dict(name="plaza_front", height_lo=9, height_hi=17, flat_roof_bias=0.6, pitch_base=29, overhang=0.27,
         colors=("#b0a898", "#c4b8a8", "#9a9080")),
    dict(name="edge_bungalow", height_lo=3, height_hi=6, flat_roof_bias=0.05, pitch_base=42, overhang=0.55,
         colors=("#e4ddce", "#d8cfbc", "#c9c0aa")),
]


_RULE_TEMPLATE = '''\
"""
Auto-generated city building rule ({name}).
Generated by pro.city.building_rules — safe to regenerate with --force-rules.
"""
from pro import *

__version__ = "1.0.0"
__description__ = "Generated city building: {name}"
__tags__ = ["city", "generated", "{name}"]

_PRESET = {{
    "height_lo": {height_lo},
    "height_hi": {height_hi},
    "flat_roof_bias": {flat_roof_bias},
    "pitch_base": {pitch_base},
    "overhang": {overhang},
    "colors": {colors!r},
}}


@rule
def Begin():
    plot = city_block({{"density": 0.5}})
    density = float(plot.get("density") or 0.5)
    p = _PRESET

    facade = choice(*p["colors"])
    height = round(
        p["height_lo"] + density * (p["height_hi"] - p["height_lo"]) * float(random(0.85, 1.15)),
        1,
    )

    color(facade)
    extrude(height)
    flat_w = min(0.95, max(0.05, p["flat_roof_bias"] * 0.5 + density * 0.5))
    chance(
        (flat_w, FlatRoof()),
        (1.0 - flat_w, PitchedRoof()),
    )


@rule
def FlatRoof():
    pass


@rule
def PitchedRoof():
    try:
        hip_roof(_PRESET["pitch_base"] + float(random(-4, 4)), _PRESET["overhang"])
    except Exception:
        pass
'''


def default_rules_dir(repo_root: Optional[str] = None) -> str:
    root = repo_root or os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    return os.path.join(root, "examples", "generated_rules")


def list_building_rules(rules_dir: str) -> List[str]:
    if not os.path.isdir(rules_dir):
        return []
    names = sorted(
        f for f in os.listdir(rules_dir)
        if f.startswith("building_") and f.endswith(".py")
    )
    return [os.path.join(rules_dir, f) for f in names]


def _building_index(filename: str) -> Optional[int]:
    """Parse N from building_N.py; None if not matching."""
    base = os.path.basename(filename)
    if not (base.startswith("building_") and base.endswith(".py")):
        return None
    mid = base[len("building_"):-len(".py")]
    if not mid.isdigit():
        return None
    return int(mid)


def next_building_rule_path(
    rules_dir: Optional[str] = None,
    start_at: int = 20,
) -> str:
    """
    Next free building_NN.py path.

    Default start_at=20 preserves preset building_00..19 used by
    ensure_building_rules / --force-rules.
    """
    rules_dir = rules_dir or default_rules_dir()
    os.makedirs(rules_dir, exist_ok=True)
    used = set()
    for path in list_building_rules(rules_dir):
        idx = _building_index(path)
        if idx is not None:
            used.add(idx)
    n = max(0, int(start_at))
    while n in used:
        n += 1
    return os.path.join(rules_dir, "building_%02d.py" % n)


def save_rule_to_pool(
    source: str,
    rules_dir: Optional[str] = None,
    start_at: int = 20,
) -> str:
    """
    Write a BCGA rule source into the town rule pool as building_NN.py.

    Returns the absolute path written. Does not call ensure_building_rules.
    """
    if not (source or "").strip():
        raise ValueError("rule source is empty")
    path = next_building_rule_path(rules_dir=rules_dir, start_at=start_at)
    with open(path, "w", encoding="utf-8") as f:
        f.write(source)
        if not source.endswith("\n"):
            f.write("\n")
    return os.path.abspath(path)


def ensure_building_rules(
    rules_dir: Optional[str] = None,
    count: int = 20,
    force: bool = False,
) -> List[str]:
    """
    Ensure `count` building_XX.py rule files exist. Returns absolute paths.
    """
    rules_dir = rules_dir or default_rules_dir()
    os.makedirs(rules_dir, exist_ok=True)
    existing = list_building_rules(rules_dir)
    if not force and len(existing) >= count:
        return existing[:count]

    presets = BUILDING_PRESETS[:count]
    if len(presets) < count:
        raise ValueError("Need at least %d BUILDING_PRESETS, have %d" % (count, len(presets)))

    paths = []
    for i, preset in enumerate(presets):
        path = os.path.join(rules_dir, "building_%02d.py" % i)
        body = _RULE_TEMPLATE.format(**preset)
        with open(path, "w", encoding="utf-8") as f:
            f.write(body)
        paths.append(path)
    return paths


def annotate_layout_rules(layout: dict, rule_paths: Sequence[str], seed: Optional[int] = None) -> dict:
    """
    Assign a rule path to each buildable plot (preferred) or block.
    Paths are stored as absolute paths for city_builder.
    """
    if not rule_paths:
        raise ValueError("rule_paths must be non-empty")
    # Keep paths as given; city_builder._resolve_rule_path absolutizes relatives.
    rules = list(rule_paths)
    rng = randomlib.Random(seed if seed is not None else layout.get("seed"))

    plots = layout.get("plots")
    if plots:
        for plot in plots:
            plot["rule"] = rng.choice(rules)
        return layout

    for block in layout.get("blocks") or []:
        if block.get("role") == "plaza":
            continue
        block["rule"] = rng.choice(rules)
    return layout
